{{/*
OstrichPKI Service Account

COMPLIANCE MAPPING:
- NIST 800-53: AC-2 (Account Management)
- NIST 800-53: AC-6 (Least Privilege)
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ostrich-pki.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ostrich-pki.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
