# OstrichPKI ConfigMap
#
# COMPLIANCE MAPPING:
# - NIST 800-53: CM-6 (Configuration Settings)

apiVersion: v1
kind: ConfigMap
metadata:
  name: ostrich-pki-config
  namespace: ostrich-pki
  labels:
    app.kubernetes.io/name: ostrich-pki
data:
  RUST_LOG: "info"
  LOG_JSON: "true"
