# OstrichPKI Service Account
#
# COMPLIANCE MAPPING:
# - NIST 800-53: AC-2 (Account Management)
# - NIST 800-53: AC-6 (Least Privilege)

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ostrich-pki
  namespace: ostrich-pki
  labels:
    app.kubernetes.io/name: ostrich-pki
automountServiceAccountToken: false
